### PR TITLE
Upgrade `wrap-ansi` and do not trim lines - fixes #20

### LINKED ISSUE #20: Leading spaces are removed from output
**example.js**:

```js
'use strict';
const logUpdate = require('log-update');

const frames = ['-', '\\', '|', '/'];
let i = 0;

setInterval(() => {
	const frame = frames[i = ++i % frames.length];

	logUpdate(
`
        ♥♥
   ${frame} unicorns ${frame}
        ♥♥
`
	);
}, 80);
```

log-update

This was probably introduced by d0ca53ec0f2ed88b18f910227eca0964738947c8.

### PR DESCRIPTION
**Pull request by SamVerschueren**
`wrap-ansi@3.0.0` with the `trim` option fixes #20 :tada:

kapture 2017-07-23 at 13 41 21

### CODE REVIEW

**Comment by sindresorhus** [comment]
Woot woot

**Comment by sindresorhus** [comment]
I noticed one small issue now:

untitled

Notice how some of the `[2]` moves.

**Comment by SamVerschueren** [comment]
Darn, good point. Not sure why that's happening. Will dive into this issue later.

**Comment by SamVerschueren** [comment]
@sindresorhus This PR solves it https://github.com/chalk/wrap-ansi/pull/21

**Pull request merged**
