### PR TITLE
only hide cursor when render is actually used - fixes #2

### LINKED ISSUE #2: Unexpected control characters when require’d and not invoked
I came across this issue when building watch functionality using the excellent elegant spinner, and it was hard to track down!

Some background: you can run `mdast` either with or without `--watch`. When not watching, nothing is written to stdout(4) normally. If you want, you can output a file to stdout(4) though.

My mother taught me to always write unit-tests, so I did: testing stdout(4) on some sample fixture to be an empty string.

Astonishment, I was, when I came to the conclusion that the tests started failing after including `log-update` (and not using it). I tracked it down to [probably this](https://github.com/sindresorhus/restore-cursor/blob/master/index.js#L6). I’m not sure exactly where it originates though (maybe useful: Bash reported stdout(4)’’s length to be 18 characters).

Back to some actionable points: I worked around this by lazy-loading `log-update`, but maybe other people will also come across this too. Is it a bug? Interested in fixing it?

:+1:

### PR DESCRIPTION
**Pull request by sindresorhus**
@wooorm How about this?

### CODE REVIEW

**Comment by wooorm** [comment]
@sindresorhus Almost, it got the string lengths down from `18` to `6`; I’ll investigate what the remain is, thanks for the work!

**Comment by wooorm** [comment]
Here’s the breakdown:

*   `log-update` requires `cli-cursor` on [L3](https://github.com/sindresorhus/log-update/blob/master/index.js#L3);
*   `cli-cursor` requires `restore-cursor` on [L2](https://github.com/sindresorhus/cli-cursor/blob/master/index.js#L2);
*   `cli-cursor` calls `restore-cursor` on [L5](https://github.com/sindresorhus/cli-cursor/blob/master/index.js#L5);
*   `restore-cursor`, when invoked, prints 6 characters to stdout on its [L6](https://github.com/sindresorhus/restore-cursor/blob/master/index.js#L6).

P.S. You can test the length of output in Bash with something like this: `result=$(node -e "require('foo')"); echo "${#result}"`

**Comment by sindresorhus** [comment]
@wooorm Yes, that's intentional. We hide the cursor on the first log and register a process.exit hook in case the process exits abstrutly we can restore the cursor. Otherwise the user is stuck with a terminal without a cursor. Not really sure of a better way. We could maybe unregister the exit hook if you call `logUpdate.done()`.

**Comment by wooorm** [comment]
@sindresorhus There’s probably a lot of ingenuity needed for that to work; I don’t understand all of it. Appreciate you taking the time! Maybe there’s indeed no way around that, if that’s the case than we’ll just have to resort to lazy-require’ing log-update.

However, when you say “on the first log”, we didn’t log anything yet in mdast though.

Also: I didn’t know the output was written on `process.exit()`, mdast itself is wrapped in a [`process.exit()`](https://github.com/wooorm/mdast/blob/8f1d7f1e0c1ed11fc9968d72e00adea3f0d4dd94/bin/mdast#L58-L62) too so it would be feasible to use `logUpdate.done()` to remove that exit listener!

**Comment by sindresorhus** [comment]
> if that’s the case than we’ll just have to resort to lazy-require’ing log-update.

Well that won't help for the process.exit logging. With this PR the process hook is only registered when you actually log something through `log-update`.

> However, when you say “on the first log”, we didn’t log anything yet in mdast though.

Did you test with this PR and not the published version?

>  I didn’t know the output was written on process.exit()

Only the restore cursor ansi escape code is.

**Comment by wooorm** [comment]
> Well that won't help for the process.exit logging. With this PR the process hook is only registered when
> you actually log something through log-update.

Are you sure? [`show`](https://github.com/sindresorhus/cli-cursor/blob/11539ca76b6d55a7451bb9750f86775044cef136/index.js#L9) and [`hide`](https://github.com/sindresorhus/cli-cursor/blob/11539ca76b6d55a7451bb9750f86775044cef136/index.js#L14) are only invoked when logging starts, but calling [`restoreCursor`](https://github.com/sindresorhus/cli-cursor/blob/11539ca76b6d55a7451bb9750f86775044cef136/index.js#L5) (done when module is first loaded) still attaches a `process.exit()` handler which is never removed

> Did you test with this PR and not the published version?

Yup!

**Comment by wooorm** [comment]
As a note: this PR does indeed change stdout(4) to be contain less (control) characters, (from `18` to `6`), but I’d like the last `6` additionally not to be output, and those seem to come from that unremovable exit listener.

Maybe that makes it a bit clearer! :smile:

**Comment by sindresorhus** [comment]
Oh. You're are indeed right. Ok, so the plan now is:

- ensure `restore-cursor` is only called once. So it only registers one exit hook: https://github.com/sindresorhus/restore-cursor/blob/master/index.js
- move the restore cursor call https://github.com/sindresorhus/cli-cursor/blob/11539ca76b6d55a7451bb9750f86775044cef136/index.js#L5 to the `hide` function.
- merge this PR

With this, is the unregistering when `.done()` is called really needed then? I don't think so.

**Comment by wooorm** [comment]
@sindresorhus Cool! :+1:

If the `done` is not needed I’m all for not adding it 😉 So if [L5](https://github.com/sindresorhus/cli-cursor/blob/11539ca76b6d55a7451bb9750f86775044cef136/index.js#L5) is moved inside the `hide()` function, that should be the case!

**Comment by sindresorhus** [comment]
@wooorm Thanks for the PRs. Appreciate it. Sorry about the trouble.

**Comment by wooorm** [comment]
No problem, will do :+1:

**Pull request closed without merging**
