### PR TITLE
Re-show cursor on render

### PR DESCRIPTION
**Pull request by dthree**
See https://github.com/sindresorhus/log-update/issues/6.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I have a feeling this might make the cursor flicker (show/hide) on some slow terminals. Will do some testing. Would adding this to `.done()` instead work for you?

**Comment by dthree** [comment]
Given the newline fix by @etiktin is applied (doesn't write `'\n`) and doesn't create other problems, this should totally work.

https://github.com/sindresorhus/log-update/pull/5#

**Comment by dthree** [comment]
Tested this in `vorpal-less` and it looks a-okay! Updated my PR.

**Comment by dthree** [comment]
@sindresorhus with this, are you okay on pulling these changes?

**Comment by sindresorhus** [comment]
Yes, will land when the other PR is landed.

**Comment by dthree** [comment]
Thanks :)

**Pull request closed without merging**
